spring.application.name=museu

# ====== Database Configuration ====== #
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/museu
spring.datasource.username=root
spring.datasource.password=alunofatec
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====== JPA / Hibernate Configuration ====== #
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.session.store-type=none
spring.jpa.database-plataform=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ====== # Thymeleaf settings # ====== #
spring.thymeleaf.cache=false

# ====== # Logging Settings # ====== #
# Define o nível de log para o seu pacote (vê até os detalhes de busca do JPA)
logging.level.br.gov.sp.fateczl.museu=DEBUG

# Salva tudo o que aparecer no console em um arquivo (ótimo para histórico)
logging.file.name=logs/sistema-museu.log

# Formato da data e hora no log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n